# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EYgibbs <- function(N, p, Y, Z, se, sp, na, GI) {
    .Call('aenetgt_EYgibbs', PACKAGE = 'aenetgt', N, p, Y, Z, se, sp, na, GI)
}

EYiYjgibbs_slow <- function(N, p, Y, Z, se, sp, na, GI) {
    .Call('aenetgt_EYiYjgibbs_slow', PACKAGE = 'aenetgt', N, p, Y, Z, se, sp, na, GI)
}

CovYiYjgibbs <- function(N, p, Y, Z, W, se, sp, EY, na, GI) {
    .Call('aenetgt_CovYiYjgibbs', PACKAGE = 'aenetgt', N, p, Y, Z, W, se, sp, EY, na, GI)
}

logistic_enet <- function(Yr, Xr, lambda, gammar, theta, binitr, delta) {
    .Call('aenetgt_logistic_enet', PACKAGE = 'aenetgt', Yr, Xr, lambda, gammar, theta, binitr, delta)
}

llj_array <- function(Zjr, Zjc, Yji, whichjretest, pxji, Se, Sp, B) {
    .Call('aenetgt_llj_array', PACKAGE = 'aenetgt', Zjr, Zjc, Yji, whichjretest, pxji, Se, Sp, B)
}

